### PR TITLE
LRG transcript mappings

### PR DESCRIPTION
**Pull request by martijnvermaat**

### CODE REVIEW

**Comment by martijnvermaat** [comment]
@LOVDnl @ifokkema  This PR comes with some changes in the transcript mapping webservices `getTranscripts`, `getTranscriptsRange`, and `getTranscriptsByGeneName`:

1. Transcripts on LRG references are now included.
2. The `getTranscriptsRange` method now optionally includes `NM` versions (set `versions=1`).
3. Transcripts on mtDNA now include the gene and transcript selector. Previously they would just show `NC_012920`, but now (for example) `NC_012920(ND1_v001)`.

For the last point, here are some webservice results that will be affected (this PR has not been deployed, so they currently show the *old* output):

- https://test.mutalyzer.nl/json/getTranscripts?chrom=chrM&build=hg19&pos=4000
- https://test.mutalyzer.nl/json/getTranscriptsByGeneName?name=TRNL1&build=hg19
- https://test.mutalyzer.nl/json/getTranscripts?chrom=chrM&build=hg19&pos=4000

I thought this could potentially impact LOVD, can you shine your light on that? :flashlight:

**Comment by martijnvermaat** [comment]
Per suggestion by Peter, we might want to skip LRG's with status PENDING (or annotate their status, but this will be more work).

**Comment by martijnvermaat** [comment]
Unfortunately I remembered incorrectly that the file we import LRG transcript mappings from contain the LRG status, but this is not the case. So to flag or skip those with PENDING status we would have to consult another source, which complicates things a bit.

ftp://ftp.ebi.ac.uk/pub/databases/lrgex/list_LRGs_transcripts_GRCh37.txt

**Comment by ifokkema** [comment]
@martijnvermaat, I checked and LOVD is exclusively using getTranscriptsAndInfo() and getTranscriptsMapping(). Can you confirm these are not affected? Thanks!

**Comment by martijnvermaat** [comment]
@ifokkema Thanks for checking.

Actually you convinced me that `getTranscriptsMapping` also needs this fix :sunglasses:, but I'll add it in a backwards compatible manner as a new field `.transcript`. As an example, [this call](https://mutalyzer.nl/json/getTranscriptsMapping?chrom=chrM&build=hg19&pos1=4000&pos2=4000&method=1) currently returns:
```json
[
  {
    "cds_start": 3307,
    "gene": "ND1",
    "name": "NC_012920",
    "stop": 4262,
    "start": 3307,
    "version": 1,
    "cds_stop": 4262,
    "orientation": "+"
  }
]
```
But with my fix it will return:
```json
[
  {
    "cds_start": 3307,
    "gene": "ND1",
    "name": "NC_012920",
    "stop": 4262,
    "start": 3307,
    "version": 1,
    "cds_stop": 4262,
    "transcript": "NC_012920.1(ND1_v001)",
    "orientation": "+"
  }
]
```
Note the only difference is the addition of the `transcript` field which you may choose to use or ignore at your own discretion.

The issue doesn't really apply to `getTranscriptsAndInfo`.

**Comment by martijnvermaat** [comment]
@ifokkema These changes are now deployed on the test server and will be on production with the next release. Thanks!

**Comment by ifokkema** [comment]
Excellent, thanks for letting me know!

**Pull request merged**
